name: Android Build
on:

  pull_request:
    types: [opened, synchronize, closed]
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
         condition: ${{ steps.set-output.outputs.condition }}
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
            with:
                token: ${{ secrets.GH_TOKEN }}
                
          - name: Print GitHub Context
            run: echo "${{ toJson(github) }}"   

          - name: Set Up JDK
            uses: actions/setup-java@v1
            with:
                java-version: 17

          - name: Build Project
            run: ./gradlew assemble

          - name: Determine condition
            id: set-output
            run: |
              # Replace with your actual logic to set the condition
              CONDITION=true  # This line sets the CONDITION variable to true
              echo "Condition is $CONDITION"
              echo "::set-output name=condition::$CONDITION"  # This line sets the output condition to the value of CONDITION 
            
    publish:
        runs-on: ubuntu-latest
        needs: build    
        if: ${{ needs.build.outputs.condition == 'true' }}
    
        steps:
          - name: Set up Ruby
            uses: ruby/setup-ruby@v1
            with:
                ruby-version: '3.0'
   
          - name: Install Fastlane
            run: gem install fastlane -NV
   
          - name: Install hub
            run: sudo apt-get install hub
   
       
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
