name: Android Build
on:
  pull_request:
    types: [opened, synchronize]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
            with:
                token: ${{ secrets.GH_TOKEN }}

          - name: Set Up JDK
            uses: actions/setup-java@v1
            with:
                java-version: 17

          - name: Run Tests
            run: ./gradlew test

          - name: Build Project
            run: ./gradlew assemble

