name: Android Build
on:

  pull_request:
    types: [opened, synchronize, closed]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
            with:
                token: ${{ secrets.GH_TOKEN }}
                
          - name: Print GitHub Context
            run: echo "${{ toJson(github) }}"   
            
          - name: Print my workflow ref head
            run: echo "${{github.head_ref}}"

          - name: Set Up JDK
            uses: actions/setup-java@v1
            with:
                java-version: 17

          - name: Build Project
            run: ./gradlew assemble
          
          - name: Trigger Release Workflow
            uses: peter-evans/repository-dispatch@v1
            with:
              token: ${{ secrets.PAT }}
              event-type: trigger-release
              client-payload: '{"branch": "${{ github.ref }}"}'   

