name: Publish to Jitpack

on:
  workflow_run:
    workflows: ["Android Build"]
    types:
      - opened
      - synchronize
      - completed

jobs:
   debug:
     runs-on: ubuntu-latest

     steps:
       - name: Install jq
         run: sudo apt-get install -y jq

       - name: Print GitHub Context
         run: |
           echo "${{ toJson(github) }}" | jq '. | {event: .event, pull_request: .pull_request}'

   