name: Publish to Jitpack

on:
  workflow_run:
    workflows: ["Android Build"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'master'

jobs:
   debug:
     runs-on: ubuntu-latest

     steps:
       - name: Print GitHub Context
         run: echo "${{ toJson(github) }}"

   publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].merged == true }}
     
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3
       with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.event.workflow_run.head_branch }}

     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: '3.0'

     - name: Install Fastlane
       run: gem install fastlane -NV

     - name: Install hub
       run: sudo apt-get install hub

    
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
