name: Publish to Jitpack

on:
  workflow_run:
    workflows: ["Android Build"]
    types:
      - opened
      - synchronize
      - completed

jobs:
   debug:
     runs-on: ubuntu-latest

     steps:
       - name: Install jq
         run: sudo apt-get install -y jq

       - name: Print GitHub Context
         run: |
           echo "${{ toJson(github) }}" | jq '. | {event: .event, pull_request: .pull_request}'

   publish:
     
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: '3.0'

     - name: Install Fastlane
       run: gem install fastlane -NV

     - name: Install hub
       run: sudo apt-get install hub

     - name: Run Fastlane
       run: fastlane android publish_to_jitpack
       evn:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}