name: Publish to Jitpack

on:
  workflow_run:
    workflows: ["Android Build"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'master'
  repository_dispatch:
    types: [trigger-release]      

jobs:
   debug:
     runs-on: ubuntu-latest

     steps:
       - name: Print GitHub Context
         run: echo "${{ toJson(github) }}"

   publish:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3
       with:
        ref: ${{ github.event.client_payload.branch || 'master' }}
     - name: Print Branch Name
       run: |
        echo "Checked out branch: ${{ github.event.client_payload.branch }}"

     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: '3.0'

     - name: Install Fastlane
       run: gem install fastlane -NV

     - name: Install hub
       run: sudo apt-get install hub

    
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
